# Go API Starter - golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

output:
  formats:
    text:
      path: stdout

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - whitespace

  disable:
    - funlen
    - gocognit
    - godox
    - lll
    - wsl
    - godot
    - mnd
    - wrapcheck
    - prealloc
    - tparallel
    - unparam
    - predeclared

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close
        - (io.Closer).Close
        - (*net/http.Response).Body.Close
        - (*encoding/json.Encoder).Encode

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    gocyclo:
      min-complexity: 20

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - commentedOutCode
        - unnecessaryBlock
        - exitAfterDefer
        - httpNoBody
        - ifElseChain
        - emptyStringTest

    gosec:
      excludes:
        - G101
        - G301
        - G304
        - G404

    misspell:
      locale: US

    nestif:
      min-complexity: 4

    exhaustive:
      default-signifies-exhaustive: true

    revive:
      rules:
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code

issues:
  uniq-by-line: true
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: warning

# goimports moved from linters to formatters in golangci-lint v2
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zareh/go-api-starter
